const fertility = [
    "Fertility Rate between ages 15-19",
    "Fertility Rate between ages 20-24",
    "Fertility Rate between ages 25-29",
    "Fertility Rate between ages 30-34",
    "Fertility Rate between ages 35-39",
    "Fertility Rate between ages 40-44",
    "Fertility Rate between ages 45-49",
    "Total Fertility Rate",
    "Gross Reproduction Rate",
    "Sex Ratio at Birth"
];

const birthDeathGrowth = [
    "Crude Birth Rate",
    "Crude Death Rate",
    "Net Migration Rate",
    "Rate of Natural Increase",
    "Growth Rate"
];

const area = [
    "Country Area"
];

const midYearPopulation = [
    "Mid-Year Population",
    "Mid-Year Population (Male)",
    "Mid-Year Population (Female)",
    "Population at Age 0",
    "Population at Age 1",
    "Population at Age 2",
    "Population at Age 3",
    "Population at Age 4",
    "Population at Age 5",
    "Population at Age 6",
    "Population at Age 7",
    "Population at Age 8",
    "Population at Age 9",
    "Population at Age 10",
    "Population at Age 11",
    "Population at Age 12",
    "Population at Age 13",
    "Population at Age 14",
    "Population at Age 15",
    "Population at Age 16",
    "Population at Age 17",
    "Population at Age 18",
    "Population at Age 19",
    "Population at Age 20",
    "Population at Age 21",
    "Population at Age 22",
    "Population at Age 23",
    "Population at Age 24",
    "Population at Age 25",
    "Population at Age 26",
    "Population at Age 27",
    "Population at Age 28",
    "Population at Age 29",
    "Population at Age 30",
    "Population at Age 31",
    "Population at Age 32",
    "Population at Age 33",
    "Population at Age 34",
    "Population at Age 35",
    "Population at Age 36",
    "Population at Age 37",
    "Population at Age 38",
    "Population at Age 39",
    "Population at Age 40",
    "Population at Age 41",
    "Population at Age 42",
    "Population at Age 43",
    "Population at Age 44",
    "Population at Age 45",
    "Population at Age 46",
    "Population at Age 47",
    "Population at Age 48",
    "Population at Age 49",
    "Population at Age 50",
    "Population at Age 51",
    "Population at Age 52",
    "Population at Age 53",
    "Population at Age 54",
    "Population at Age 55",
    "Population at Age 56",
    "Population at Age 57",
    "Population at Age 58",
    "Population at Age 59",
    "Population at Age 60",
    "Population at Age 61",
    "Population at Age 62",
    "Population at Age 63",
    "Population at Age 64",
    "Population at Age 65",
    "Population at Age 66",
    "Population at Age 67",
    "Population at Age 68",
    "Population at Age 69",
    "Population at Age 70",
    "Population at Age 71",
    "Population at Age 72",
    "Population at Age 73",
    "Population at Age 74",
    "Population at Age 75",
    "Population at Age 76",
    "Population at Age 77",
    "Population at Age 78",
    "Population at Age 79",
    "Population at Age 80",
    "Population at Age 81",
    "Population at Age 82",
    "Population at Age 83",
    "Population at Age 84",
    "Population at Age 85",
    "Population at Age 86",
    "Population at Age 87",
    "Population at Age 88",
    "Population at Age 89",
    "Population at Age 90",
    "Population at Age 91",
    "Population at Age 92",
    "Population at Age 93",
    "Population at Age 94",
    "Population at Age 95",
    "Population at Age 96",
    "Population at Age 97",
    "Population at Age 98",
    "Population at Age 99",
    "Population at Age 100"   
];

const mortality = [
    "Infant Mortality Rate (Both Sexes)",
    "Infant Mortality Rate (Male)",
    "Infant Mortality Rate (Female)",
    "Life Expectancy at Birth (Both Sexes)",
    "Life Expectancy at Birth (Male)",
    "Life Expectancy at Birth (Female)",
    "Under-5 Mortality Rate (Both Sexes)",
    "Under-5 Mortality Rate (Male)",
    "Under-5 Mortality Rate (Female)",
    "Child Mortality Rate (Both Sexes)",
    "Child Mortality Rate (Male)",
    "Child Mortality Rate (Female)"
];

const incomeStats = [
    "Income index",
    "Domestic Credit Provided by Financial Sector",
    "Estimated Gross National Income per Capita (female)",
    "Estimated Gross National Income per Capita (male)",
    "GDP per Capita",
    "Gross Domestic Product (GDP) (total)",
    "Gross Fixed Capital Formation",
    "Gross National Income (GNI) per Capita",
    "Labour Share of GDP"
]

export const Statistics: string[] = [
    ...fertility,
    ...birthDeathGrowth,
    ...midYearPopulation,
    ...mortality,
    ...incomeStats
];